server:
  port: 8081

spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库url
    url: jdbc:mysql://47.102.204.221:3306/seckill?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
  redis:
    redisson:
      file: classpath:config/redisson.yml


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.team.dao

nacos:
  config:
    server-addr: 47.98.175.227:8848